{
 "title": "NSBDemo",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "API Instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"api:3030\",job=\"api\"}",
     "legendFormat": "API Instance"
    }
   ]
  },
  {
   "title": "Notification Handler",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"emailnotificationhandler:3031\",job=\"emailnotificationhandler\"}",
     "legendFormat": "API Instance"
    }
   ]
  },
  {
   "title": "Platform Handler",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"platformhandler:3032\",job=\"platformhandler\"}",
     "legendFormat": "API Instance"
    }
   ]
  },
  {
   "title": "Sagas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"sagas:3033\",job=\"sagas\"}",
     "legendFormat": "API Instance"
    }
   ]
  },
  {
   "title": "Notification Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "average rate" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nsbdemo_notification_counter{instance=\"emailnotificationhandler:3031\",job=\"emailnotificationhandler\",status=\"sent\"}[5m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "API",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "average rate" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nsbdemo_api_request_counter{instance=\"api:3030\",job=\"api\",status=\"received\"}[5m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Sagas",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "average rate" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nsbdemo_sagas_event_counter{instance=\"sagas:3033\",job=\"sagas\",status=\"received\"}[5m]))",
     "legendFormat": "received"
    },
    {
     "expr": "avg(rate(nsbdemo_sagas_event_counter{instance=\"sagas:3033\",job=\"sagas\",status=\"processed\"}[5m]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "Platform Handler",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nsbdemo_platform_event_counter{instance=\"platformhandler:3032\",job=\"platformhandler\",status=\"received\"}[5m]))",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}